//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace BlazorServerDevExpXAF.Module.BusinessObjects.XPO.DxSample
{

    public partial class Order : XPObject
    {
        string _ProductName;
        [Size(200)]
        public string ProductName
        {
            get { return _ProductName; }
            set { SetPropertyValue<string>(nameof(ProductName), ref _ProductName, value); }
        }
        DateTime _OrderDate;
        public DateTime OrderDate
        {
            get { return _OrderDate; }
            set { SetPropertyValue<DateTime>(nameof(OrderDate), ref _OrderDate, value); }
        }
        decimal _Freight;
        public decimal Freight
        {
            get { return _Freight; }
            set { SetPropertyValue<decimal>(nameof(Freight), ref _Freight, value); }
        }
        Customer _Customer;
        [Association(@"OrderReferencesCustomer")]
        public Customer Customer
        {
            get { return _Customer; }
            set { SetPropertyValue<Customer>(nameof(Customer), ref _Customer, value); }
        }
    }

}
